# https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--
    groups:
      patch-and-minor:
        IDENTIFIER: "patch-and-minor-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

      major-updates:
        IDENTIFIER: "major-updates"
        patterns:
          - "*"
        update-types:
          - "major"
