# https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--
    groups:
      # https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#%E4%BE%8B-2-%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E3%81%8C%E9%99%A4%E5%A4%96%E3%81%95%E3%82%8C%E3%81%9F%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E5%8C%96%E3%81%95%E3%82%8C%E3%81%9F%E6%9B%B4%E6%96%B0%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
