# https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # パッチ・マイナーの更新を週1回
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    pull-request-branch-name:
      prefix: "weekly-update/" # 週次PRのプレフィックス

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly" # メジャーアップデートを月1回
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    pull-request-branch-name:
      prefix: "monthly-update/"
