# https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      patch-and-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
        schedule:
          interval: "weekly" # パッチ・マイナー更新は週1回
        pull-request-branch-name:
          prefix: "weekly-update/"

      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
        schedule:
          interval: "monthly" # メジャーアップデートは月1回
        pull-request-branch-name:
          prefix: "monthly-update/"
