version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - APP_NAME="nextjs-express"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $APP_NAME:$IMAGE_TAG -f Dockerfile.prod .
      - docker tag $APP_NAME:$IMAGE_TAG $IMAGE_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
