version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_TAG=v$(date +%Y%m%d%H%M%S)
      - APP_NAME="nextjs-express"
      # Enable BuildKit
      - export DOCKER_BUILDKIT=1
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  build:
    commands:
      - echo "Building the Docker image..."
      # buildxの場合はtagにECRのURIを含める必要がある
      # - docker buildx build --cache-from=type=registry,ref=$ECR_REPO_URI:build-cache --cache-to=type=registry,ref=$ECR_REPO_URI:build-cache,mode=max,image-manifest=true,oci-mediatypes=true -t $ECR_REPO_URI:$IMAGE_TAG -f Dockerfile.prod --push .

      # inline cache
      - docker buildx build --load --cache-to=type=inline --cache-from=type=registry,ref=$ECR_REPO_URI:v20250325131458 -f Dockerfile.prod -t $APP_NAME:$IMAGE_TAG .

      - docker tag $APP_NAME:$IMAGE_TAG $ECR_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
